/* ****************************************************************
 * Athr(s): Harry Direen PhD,
 * DireenTech Inc.  (www.DireenTech.com)
 * Date: Jan. 13, 2018
 *
 * NeuroGroove IMU Communications Interface
 *******************************************************************/

#ifndef VIDERE_DEV_IMUCOMMMANAGER_H
#define VIDERE_DEV_IMUCOMMMANAGER_H

#include <iostream>
#include <string>
#include <memory>
#include <vector>
#include <sstream>
#include <unordered_map>
#include <RabitManager.h>
#include <RabitMessageQueue.h>
#include <ManagerStatusMessage.h>
#include <ManagerControlMessage.h>
#include <ManagerStats.h>
#include <ManagerStatusMessage.h>
#include <opencv2/core.hpp>
#include "global_defines.h"
#include "all_manager_message.h"
#include "../../Utils/config_data.h"
#include "../../Utils/logger.h"
#include "../../Utils/timing.h"
#include "RS232Comm.h"
#include "SerialCommMessage.h"
#include "IMU_TxMessageFormatter.h"
#include "IMU_RxMessageParser.h"
#include "IMUCalibration.h"

// Manually include this file that has been autogenerated
#include "IMUCommManagerWSRMgr.h"

using namespace Rabit;
using namespace IMU_SensorNS;

namespace videre
{


    class IMUCommManager : public IMUCommManagerWSRMgr
    {

    private:
        //Logging System
        log4cxx::LoggerPtr log4cpp_;

        std::shared_ptr<ConfigData> _config_sptr;

        dtiRS232Comm::RS232Comm _rs232Comm;

        IMU_SensorNS::IMU_RxMessageParser _imuRxMessageParser;

        IMU_SensorNS::IMU_TxMessageFormatter _imuTxMsgFormatter;

        std::shared_ptr<IMUCommandResponseMessage> _imuCommandMessage;

        RabitStopWatch _txMsgStopwatch;

        bool _accelEnabled = false;
        bool _gyroEnabled = false;

        bool _rs232CommStarted = false;

        //IMUStartupSequenceState_e _IMUStartupSequenceState = IMUStartupSequenceState_e::IMUSSS_Start;
        int _IMUStartupSequenceState = 0;

        bool _IMUStartupComplete = false;

        IMU_SensorNS::IMUCalibration _fixedIMUCalData;
        IMU_SensorNS::IMUCalibration _headIMUCalData;

        std::string _imuCalDir = "IMUCalData";
        std::string _imuFixedCalFilename = "IMUFixedCalData.ini";
        std::string _imuHeadCalFilename = "IMUHeadCalData.ini";



    public:
        IMUCommManager(std::string name, std::shared_ptr<ConfigData> config);

        virtual void Initialize();

        bool openCommPort(std::string commPort, int baudRate, bool logResults = true);

        void closeCommPort();

        bool transmitMessage(std::string msg);

        bool transmitMessage(char *msg);

        virtual void Startup() final;

        virtual void ExecuteUnitOfWork() final;

        virtual void Shutdown() final;

        bool IMU_StartupControlSequence();
     };

}
#endif //VIDERE_DEV_IMUCOMMMANAGER_H
