
// This file has been generated by the GUI designer. Do not modify.
namespace VisionSystemGtkViewer
{
	public partial class ManagerStats
	{
		private global::Gtk.Frame MgrStatsFrame;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.TextView tbMgrName;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.TextView tbMgrState;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.TextView tbMgrErrorCode;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Button btnResetMgrStats;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.TextView tbMgrNoExecCycles;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.TextView tbMgrTime;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.TextView tbMgrWakupCallsAwake;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.TextView tbMgrWakupCallsAsleep;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.TextView tbMgrExecTimeAve;
		
		private global::Gtk.TextView tbMgrExecTimeMax;
		
		private global::Gtk.TextView tbMgrExecTimeMin;
		
		private global::Gtk.TextView tbMgrExecTimeTotal;
		
		private global::Gtk.TextView tbMgrSleepTimeAve;
		
		private global::Gtk.TextView tbMgrSleepTimeMax;
		
		private global::Gtk.TextView tbMgrSleepTimeMin;
		
		private global::Gtk.TextView tbMgrSleepTimeTotal;
		
		private global::Gtk.Label GtkLabel1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VisionSystemGtkViewer.ManagerStats
			global::Stetic.BinContainer.Attach (this);
			this.Name = "VisionSystemGtkViewer.ManagerStats";
			// Container child VisionSystemGtkViewer.ManagerStats.Gtk.Container+ContainerChild
			this.MgrStatsFrame = new global::Gtk.Frame ();
			this.MgrStatsFrame.Name = "MgrStatsFrame";
			this.MgrStatsFrame.ShadowType = ((global::Gtk.ShadowType)(1));
			this.MgrStatsFrame.BorderWidth = ((uint)(2));
			// Container child MgrStatsFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Mrg Name: ");
			this.hbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.tbMgrName = new global::Gtk.TextView ();
			this.tbMgrName.CanFocus = true;
			this.tbMgrName.Name = "tbMgrName";
			this.tbMgrName.Editable = false;
			this.hbox3.Add (this.tbMgrName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tbMgrName]));
			w2.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("State: ");
			this.hbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.tbMgrState = new global::Gtk.TextView ();
			this.tbMgrState.CanFocus = true;
			this.tbMgrState.Name = "tbMgrState";
			this.tbMgrState.Editable = false;
			this.hbox3.Add (this.tbMgrState);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tbMgrState]));
			w4.Position = 3;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Error Code: ");
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.tbMgrErrorCode = new global::Gtk.TextView ();
			this.tbMgrErrorCode.CanFocus = true;
			this.tbMgrErrorCode.Name = "tbMgrErrorCode";
			this.tbMgrErrorCode.Editable = false;
			this.tbMgrErrorCode.CursorVisible = false;
			this.hbox3.Add (this.tbMgrErrorCode);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.tbMgrErrorCode]));
			w6.Position = 5;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnResetMgrStats = new global::Gtk.Button ();
			this.btnResetMgrStats.CanFocus = true;
			this.btnResetMgrStats.Name = "btnResetMgrStats";
			this.btnResetMgrStats.UseUnderline = true;
			this.btnResetMgrStats.Label = global::Mono.Unix.Catalog.GetString ("Reset Stats");
			this.hbox4.Add (this.btnResetMgrStats);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnResetMgrStats]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Number Execute Cycles: ");
			this.hbox4.Add (this.label8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.tbMgrNoExecCycles = new global::Gtk.TextView ();
			this.tbMgrNoExecCycles.CanFocus = true;
			this.tbMgrNoExecCycles.Name = "tbMgrNoExecCycles";
			this.tbMgrNoExecCycles.Editable = false;
			this.hbox4.Add (this.tbMgrNoExecCycles);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.tbMgrNoExecCycles]));
			w10.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Execute Time (Sec): ");
			this.hbox4.Add (this.label9);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label9]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.tbMgrTime = new global::Gtk.TextView ();
			this.tbMgrTime.CanFocus = true;
			this.tbMgrTime.Name = "tbMgrTime";
			this.tbMgrTime.Editable = false;
			this.hbox4.Add (this.tbMgrTime);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.tbMgrTime]));
			w12.Position = 4;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Wake-up Calls: ");
			this.hbox5.Add (this.label10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label10]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("While Awake");
			this.hbox5.Add (this.label12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label12]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.tbMgrWakupCallsAwake = new global::Gtk.TextView ();
			this.tbMgrWakupCallsAwake.CanFocus = true;
			this.tbMgrWakupCallsAwake.Name = "tbMgrWakupCallsAwake";
			this.tbMgrWakupCallsAwake.Editable = false;
			this.hbox5.Add (this.tbMgrWakupCallsAwake);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.tbMgrWakupCallsAwake]));
			w16.Position = 2;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("While Asleep");
			this.hbox5.Add (this.label11);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label11]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.tbMgrWakupCallsAsleep = new global::Gtk.TextView ();
			this.tbMgrWakupCallsAsleep.CanFocus = true;
			this.tbMgrWakupCallsAsleep.Name = "tbMgrWakupCallsAsleep";
			this.tbMgrWakupCallsAsleep.Editable = false;
			this.hbox5.Add (this.tbMgrWakupCallsAsleep);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.tbMgrWakupCallsAsleep]));
			w18.Position = 4;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("     Min     ");
			this.label13.Justify = ((global::Gtk.Justification)(2));
			this.table1.Add (this.label13);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.label13]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("     Max     ");
			this.label14.Justify = ((global::Gtk.Justification)(2));
			this.table1.Add (this.label14);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label14]));
			w21.LeftAttach = ((uint)(2));
			w21.RightAttach = ((uint)(3));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("     Ave         ");
			this.label15.Justify = ((global::Gtk.Justification)(2));
			this.table1.Add (this.label15);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.label15]));
			w22.LeftAttach = ((uint)(3));
			w22.RightAttach = ((uint)(4));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("    Total    ");
			this.label16.Justify = ((global::Gtk.Justification)(2));
			this.table1.Add (this.label16);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1 [this.label16]));
			w23.LeftAttach = ((uint)(4));
			w23.RightAttach = ((uint)(5));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Execute Time (Sec)");
			this.table1.Add (this.label17);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.label17]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Sleep Time (Sec)");
			this.table1.Add (this.label18);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.label18]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrExecTimeAve = new global::Gtk.TextView ();
			this.tbMgrExecTimeAve.CanFocus = true;
			this.tbMgrExecTimeAve.Name = "tbMgrExecTimeAve";
			this.tbMgrExecTimeAve.Editable = false;
			this.tbMgrExecTimeAve.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrExecTimeAve);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrExecTimeAve]));
			w26.TopAttach = ((uint)(1));
			w26.BottomAttach = ((uint)(2));
			w26.LeftAttach = ((uint)(3));
			w26.RightAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrExecTimeMax = new global::Gtk.TextView ();
			this.tbMgrExecTimeMax.CanFocus = true;
			this.tbMgrExecTimeMax.Name = "tbMgrExecTimeMax";
			this.tbMgrExecTimeMax.Editable = false;
			this.tbMgrExecTimeMax.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrExecTimeMax);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrExecTimeMax]));
			w27.TopAttach = ((uint)(1));
			w27.BottomAttach = ((uint)(2));
			w27.LeftAttach = ((uint)(2));
			w27.RightAttach = ((uint)(3));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrExecTimeMin = new global::Gtk.TextView ();
			this.tbMgrExecTimeMin.CanFocus = true;
			this.tbMgrExecTimeMin.Name = "tbMgrExecTimeMin";
			this.tbMgrExecTimeMin.Editable = false;
			this.tbMgrExecTimeMin.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrExecTimeMin);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrExecTimeMin]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrExecTimeTotal = new global::Gtk.TextView ();
			this.tbMgrExecTimeTotal.CanFocus = true;
			this.tbMgrExecTimeTotal.Name = "tbMgrExecTimeTotal";
			this.tbMgrExecTimeTotal.Editable = false;
			this.tbMgrExecTimeTotal.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrExecTimeTotal);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrExecTimeTotal]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(4));
			w29.RightAttach = ((uint)(5));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrSleepTimeAve = new global::Gtk.TextView ();
			this.tbMgrSleepTimeAve.CanFocus = true;
			this.tbMgrSleepTimeAve.Name = "tbMgrSleepTimeAve";
			this.tbMgrSleepTimeAve.Editable = false;
			this.tbMgrSleepTimeAve.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrSleepTimeAve);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrSleepTimeAve]));
			w30.TopAttach = ((uint)(2));
			w30.BottomAttach = ((uint)(3));
			w30.LeftAttach = ((uint)(3));
			w30.RightAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrSleepTimeMax = new global::Gtk.TextView ();
			this.tbMgrSleepTimeMax.CanFocus = true;
			this.tbMgrSleepTimeMax.Name = "tbMgrSleepTimeMax";
			this.tbMgrSleepTimeMax.Editable = false;
			this.tbMgrSleepTimeMax.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrSleepTimeMax);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrSleepTimeMax]));
			w31.TopAttach = ((uint)(2));
			w31.BottomAttach = ((uint)(3));
			w31.LeftAttach = ((uint)(2));
			w31.RightAttach = ((uint)(3));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrSleepTimeMin = new global::Gtk.TextView ();
			this.tbMgrSleepTimeMin.CanFocus = true;
			this.tbMgrSleepTimeMin.Name = "tbMgrSleepTimeMin";
			this.tbMgrSleepTimeMin.Editable = false;
			this.tbMgrSleepTimeMin.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrSleepTimeMin);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrSleepTimeMin]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.tbMgrSleepTimeTotal = new global::Gtk.TextView ();
			this.tbMgrSleepTimeTotal.CanFocus = true;
			this.tbMgrSleepTimeTotal.Name = "tbMgrSleepTimeTotal";
			this.tbMgrSleepTimeTotal.Editable = false;
			this.tbMgrSleepTimeTotal.Justification = ((global::Gtk.Justification)(1));
			this.table1.Add (this.tbMgrSleepTimeTotal);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.tbMgrSleepTimeTotal]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(4));
			w33.RightAttach = ((uint)(5));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w34.Position = 3;
			w34.Expand = false;
			w34.Fill = false;
			this.GtkAlignment.Add (this.vbox1);
			this.MgrStatsFrame.Add (this.GtkAlignment);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Manager Stats</b>");
			this.GtkLabel1.UseMarkup = true;
			this.MgrStatsFrame.LabelWidget = this.GtkLabel1;
			this.Add (this.MgrStatsFrame);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnResetMgrStats.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnBtnResetMgrStatsButtonPressEvent);
			this.btnResetMgrStats.Clicked += new global::System.EventHandler (this.OnBtnResetMgrStatsClicked);
		}
	}
}
