/* ****************************************************************
 * Athr(s): Harry Direen PhD,
 * DireenTech Inc.  (www.DireenTech.com)
 * Date: Jan. 13, 2018
 *
 * NeuroGroove IMU Communications Interface
 *******************************************************************/

#ifndef VIDERE_DEV_ROBOTARMMANAGER_H
#define VIDERE_DEV_ROBOTARMMANAGER_H

#include <iostream>
#include <string>
#include <memory>
#include <vector>
#include <sstream>
#include <unordered_map>
#include <RabitManager.h>
#include <RabitMessageQueue.h>
#include <ManagerStatusMessage.h>
#include <ManagerControlMessage.h>
#include <ManagerStats.h>
#include <ManagerStatusMessage.h>
#include <opencv2/core.hpp>
#include "global_defines.h"
#include "all_manager_message.h"
#include "../../Utils/config_data.h"
#include "../../Utils/logger.h"
#include "../../Utils/timing.h"
#include "RS232Comm.h"
#include "SerialCommMessage.h"
#include "RobotArm_TxMessageFormatter.h"
#include "RobotArm_RxMessageParser.h"

// Manually include this file that has been autogenerated
#include "RobotArmManagerWSRMgr.h"

using namespace Rabit;

namespace videre
{

    class RobotArmManager : public RobotArmManagerWSRMgr
    {

    private:
        //Logging System
        log4cxx::LoggerPtr log4cpp_;

        std::shared_ptr<ConfigData> _config_sptr;

        dtiRS232Comm::RS232Comm _rs232Comm;

        RobotArm_RxMessageParser _imuRxMessageParser;

        RobotArm_TxMessageFormatter _imuTxMessageFormatter;

        RabitStopWatch _txMsgStopwatch;

        bool _accelEnabled = false;
        bool _gyroEnabled = false;


    public:
        RobotArmManager(std::string name, std::shared_ptr<ConfigData> config);

        virtual void Initialize();

        bool openCommPort(std::string commPort, int baudRate, bool logResults = true);

        void closeCommPort();

        bool transmitMessage(std::string msg);

        bool transmitMessage(char *msg);

        virtual void ExecuteUnitOfWork() final;

        virtual void Shutdown() final;

    };

}


#endif //VIDERE_DEV_ROBOTARMMANAGER_H
